# DEV
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/global_schema?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&characterSetResults=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  hibernate:
    config:
      xml: hibernate-dev.cfg.xml
  redis:
    host: 127.0.0.1
    password: sivaospassword
    port: 6379
    sentinel:
      master:
        name: sivaos
      host-and-port: 13.232.155.79:26379;13.232.155.88:26379;13.232.154.78:26379
# Hibernate Log levels
logging:
  pattern:
    #console: "%blue(%d{yyyy-MM-dd HH:mm:ss}) %cyan([%mdc]) %highlight(%level) %yellow(%logger{15}) -> %msg%n"
    console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(%logger{0}){blue} %clr(%m){faint}%n %yellow(%logger{15}) -> %msg%n"
    rolling-file-name: logs/dev-sivaos-%d{yyyy-MM-dd}.%i.log
  file:
    name: "logs/dev-sivaos.log"

